wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1671517289.396366
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.8.16
      5: 0.13.7
      8:
      - 5
created_at:
  desc: null
  value: '2022-12-20T05:46:05'
fine_tuned_model:
  desc: null
  value: curie:ft-new-york-university-2022-12-20-05-52-28
hyperparams:
  desc: null
  value:
    batch_size: 2
    learning_rate_multiplier: 0.1
    n_epochs: 4
    prompt_loss_weight: 0.1
id:
  desc: null
  value: ft-jxFTOONXtEE9wOuUXnAghvgu
model:
  desc: null
  value: curie
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-HjCdtP78SRqgBYjvhQlUd26I
result_files:
  desc: null
  value:
    bytes: 34563
    created_at: 1671515548
    filename: compiled_results.csv
    id: file-74QP24WVvHBIVDKsLJBddrZE
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 115013
    created_at: 1671515161
    filename: dw_train.jsonl
    id: file-5SMavY9JBjqVB6od8ciErh1w
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1671515549
validation_files:
  desc: null
  value:
    bytes: 11485
    created_at: 1671515165
    filename: dw_valid.jsonl
    id: file-ZMYXvBPISEsBFgO3CTadu5fK
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
